include $(RIOTMAKE)/color.inc.mk
$(shell $(COLOR_ECHO) "$(COLOR_PURPLE)Attention! Module PUF SRAM requires power-off\
	in order to generate a high-entropy number$(COLOR_RESET)" 1>&2)

include $(RIOTBASE)/Makefile.base
